#Config file for calculating 3D position of Object in bounding box

depth_topic: "/kinect2/hd/points"
boundingbox_sub: "/darknet_ros/bounding_boxes"
result_topic: "/detection/center_depth"
tf_frame_source: "kinect2_rgb_optical_frame"
tf_frame_target: "map"
map_file_path: "../data/test_Thomas.json"
service_get_current_area_name: "get_current_area_in_map"
service_get_objects_in_room: "get_objects_list"
service_get_people_in_room: "get_people_list_in_room"
people_detection_topic: "/people_meta_info_only"
service_reset_objects: "reset_object_files"
service_building_map_area: "building_map_area"
service_saving_map_area: "saving_map_area"
path_to_data_temp: "../../../../data/world_mng/temp/"
path_to_data_ipt: "../../../../data/world_mng/interest_points/"
