#Config file for calculating 3D position of Object in bounding box

depth_topic: "/camera/depth/points"
boundingbox_sub: "/darknet_ros/bounding_boxes"
result_topic: "/detection/center_depth"
tf_frame_source: "camera_depth_link"
tf_frame_target: "map"
